services:
  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      LANG: ja_JP.UTF-8
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
  #  localstack:
  #    image: localstack/localstack
  #    environment:
  #      PERSISTENCE: 1
  #      LOCALSTACK_HOST: host.docker.internal
  #    ports:
  #      - '4566:4566'
  #    volumes:
  #      - /tmp/localstack:/var/lib/localstack
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
