spring:
  profiles: stg
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sampledb
    username: root
    password: passw0rd
  mail:
    protocol: smtp
    host: 127.0.0.1
    port: 25
    username: test
    password: test
    properties:
      mail:
        from: from@test.com
logging:
  level:
    org.springframework.web: INFO

####
# アプリケーションの設定
application:
  fileUploadLocation: build/sample
